import type {
  Holding,
  Transaction,
  AllocationTarget,
  StressScenario,
} from "./types";

/* ─────────────────────────────────────────────────────────
   Leadway Holdings Group — Portfolio Reference Data
   All monetary values in NGN millions.
   Market values sourced from Leadway Quanta Valuation Engine (26 May 2026).
   ───────────────────────────────────────────────────────── */
export const HOLDINGS: Holding[] = [
  /* ── SUBSIDIARIES / PRIVATE EQUITY ────────────────────── */
  {
    id: "HIG",
    name: "Leadway Assurance",
    assetClass: "Private Equity",
    sector: "Insurance",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Leadway Holdings Ltd",
    quantity: 1,
    costPrice: 98_400,
    costBasis: 98_400,
    marketValue: 118_500,
    ytdReturn: 0.145,
    beta: 0.82,
    dividendYield: 0.038,
  },
  {
    id: "HLA",
    name: "Leadway Pensure PFA",
    assetClass: "Private Equity",
    sector: "Insurance",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Leadway Holdings Ltd",
    quantity: 1,
    costPrice: 61_200,
    costBasis: 61_200,
    marketValue: 72_400,
    ytdReturn: 0.128,
    beta: 0.78,
    dividendYield: 0.032,
  },
  {
    id: "HET",
    name: "Leadway Energy Ventures",
    assetClass: "Private Equity",
    sector: "Energy",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Leadway Holdings Ltd",
    quantity: 1,
    costPrice: 84_600,
    costBasis: 84_600,
    marketValue: 98_200,
    ytdReturn: 0.16,
    beta: 1.05,
  },
  {
    id: "HTG",
    name: "Leadway Technologies",
    assetClass: "Private Equity",
    sector: "Technology",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Leadway Holdings Ltd",
    quantity: 1,
    costPrice: 22_500,
    costBasis: 22_500,
    marketValue: 28_000,
    ytdReturn: 0.22,
    beta: 1.15,
  },
  {
    id: "AGF3",
    name: "Africa Growth Fund III",
    assetClass: "Private Equity",
    sector: "Diversified PE",
    geography: "Pan-Africa",
    currency: "USD",
    issuer: "African Capital Alliance",
    quantity: 1,
    costPrice: 56_800,
    costBasis: 56_800,
    marketValue: 64_000,
    ytdReturn: 0.108,
    beta: 0.88,
  },

  /* ── LISTED EQUITIES ───────────────────────────────────── */
  {
    id: "TCP",
    name: "Transcorp Plc",
    assetClass: "Equity",
    sector: "Conglomerate",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Transcorp Plc",
    quantity: 8_200_000_000,
    costPrice: 5.82,
    costBasis: 47_724,
    marketValue: 68_000,
    marketPrice: 8.29,
    ytdReturn: 0.184,
    beta: 1.12,
    dividendYield: 0.021,
  },
  {
    id: "TCH",
    name: "Transcorp Hotels Plc",
    assetClass: "Equity",
    sector: "Hospitality",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Transcorp Hotels Plc",
    quantity: 3_750_000_000,
    costPrice: 8.44,
    costBasis: 31_650,
    marketValue: 42_000,
    marketPrice: 11.2,
    ytdReturn: 0.134,
    beta: 0.94,
    dividendYield: 0.018,
  },
  {
    id: "UCA",
    name: "United Capital Plc",
    assetClass: "Equity",
    sector: "Financial Services",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "United Capital Plc",
    quantity: 1_580_000_000,
    costPrice: 12.68,
    costBasis: 20_034,
    marketValue: 24_000,
    marketPrice: 15.19,
    ytdReturn: 0.098,
    beta: 0.96,
    dividendYield: 0.042,
  },
  {
    id: "APG",
    name: "Africa Prudential Plc",
    assetClass: "Equity",
    sector: "Financial Services",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Africa Prudential Plc",
    quantity: 580_000_000,
    costPrice: 13.4,
    costBasis: 7_772,
    marketValue: 9_500,
    marketPrice: 16.38,
    ytdReturn: 0.062,
    beta: 0.78,
    dividendYield: 0.055,
  },
  {
    id: "HBK",
    name: "Heritage Bank",
    assetClass: "Equity",
    sector: "Banking",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Heritage Bank Plc",
    quantity: 1_820_000_000,
    costPrice: 7.1,
    costBasis: 12_922,
    marketValue: 16_500,
    marketPrice: 9.07,
    ytdReturn: 0.075,
    beta: 1.08,
    dividendYield: 0.028,
  },

  /* ── REAL ESTATE ───────────────────────────────────────── */
  {
    id: "HPL",
    name: "Leadway Place HQ Lagos",
    assetClass: "Real Estate",
    sector: "Commercial Real Estate",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Leadway Properties Ltd",
    quantity: 1,
    costPrice: 62_400,
    costBasis: 62_400,
    marketValue: 72_000,
    ytdReturn: 0.094,
    beta: 0.42,
  },
  {
    id: "HTA",
    name: "Leadway Tower Abuja",
    assetClass: "Real Estate",
    sector: "Commercial Real Estate",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Leadway Properties Ltd",
    quantity: 1,
    costPrice: 38_600,
    costBasis: 38_600,
    marketValue: 46_500,
    ytdReturn: 0.105,
    beta: 0.38,
  },

  /* ── FIXED INCOME ──────────────────────────────────────── */
  {
    id: "FGNB31",
    name: "FGN Bond 2031 (15.5%)",
    assetClass: "Fixed Income",
    sector: "Sovereign",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Federal Govt. of Nigeria",
    quantity: 1_000_000,
    costPrice: 76_200,
    costBasis: 76_200,
    marketValue: 78_400,
    marketPrice: 78_400,
    ytdReturn: 0.062,
    beta: 0.08,
    dividendYield: 0.155,
  },
  {
    id: "FGNB33",
    name: "FGN Bond 2033 (16.25%)",
    assetClass: "Fixed Income",
    sector: "Sovereign",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Federal Govt. of Nigeria",
    quantity: 800_000,
    costPrice: 27_800,
    costBasis: 27_800,
    marketValue: 23_400,
    marketPrice: 29_250,
    ytdReturn: 0.054,
    beta: 0.09,
    dividendYield: 0.1625,
  },
  {
    id: "DGB26",
    name: "Dangote Industries Bond 2026",
    assetClass: "Fixed Income",
    sector: "Corporate",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Dangote Industries Ltd",
    quantity: 250_000,
    costPrice: 72_400,
    costBasis: 72_400,
    marketValue: 18_500,
    marketPrice: 74_000,
    ytdReturn: 0.041,
    beta: 0.14,
    dividendYield: 0.1475,
  },

  /* ── CASH & EQUIVALENTS ────────────────────────────────── */
  {
    id: "CBN182",
    name: "T-Bills 182-Day (May 2026)",
    assetClass: "Cash",
    sector: "Sovereign",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Central Bank of Nigeria",
    quantity: 1,
    costPrice: 18_200,
    costBasis: 18_200,
    marketValue: 18_200,
    ytdReturn: 0.09,
    beta: 0.0,
  },
  {
    id: "CBN91",
    name: "T-Bills 91-Day (Apr 2026)",
    assetClass: "Cash",
    sector: "Sovereign",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Central Bank of Nigeria",
    quantity: 1,
    costPrice: 12_000,
    costBasis: 12_000,
    marketValue: 12_000,
    ytdReturn: 0.088,
    beta: 0.0,
  },

  /* ── ALTERNATIVES ──────────────────────────────────────── */
  {
    id: "SFJ",
    name: "Strategic FinTech JV",
    assetClass: "Alternatives",
    sector: "Technology",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Leadway Holdings / Partners",
    quantity: 1,
    costPrice: 6_800,
    costBasis: 6_800,
    marketValue: 8_200,
    ytdReturn: 0.172,
    beta: 1.22,
  },
  {
    id: "LIF",
    name: "Lagos Infrastructure Fund",
    assetClass: "Alternatives",
    sector: "Infrastructure",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Lagos State / Partners",
    quantity: 1,
    costPrice: 28_400,
    costBasis: 28_400,
    marketValue: 32_000,
    ytdReturn: 0.092,
    beta: 0.48,
  },
];

/* ─────────────────────────────────────────────────────────
   Strategic Allocation Targets
   ───────────────────────────────────────────────────────── */
export const TARGETS: AllocationTarget[] = [
  { assetClass: "Private Equity", targetPct: 42, limitPct: 55 },
  { assetClass: "Equity", targetPct: 19, limitPct: 30 },
  { assetClass: "Fixed Income", targetPct: 14, limitPct: 25 },
  { assetClass: "Real Estate", targetPct: 14, limitPct: 20 },
  { assetClass: "Cash", targetPct: 4, limitPct: 15 },
  { assetClass: "Alternatives", targetPct: 5, limitPct: 12 },
];

/* ─────────────────────────────────────────────────────────
   Transaction History
   ───────────────────────────────────────────────────────── */
export const TRANSACTIONS: Transaction[] = [
  {
    id: "TXN-0241",
    date: "2026-05-25",
    type: "Buy",
    holdingId: "FGNB33",
    assetName: "FGN Bond 2033",
    quantity: 100,
    price: 29_250,
    amount: -2_925,
    status: "Settled",
    notes: "Duration extension trade, tactical fixed income overlay",
  },
  {
    id: "TXN-0240",
    date: "2026-05-25",
    type: "Sell",
    holdingId: "HBK",
    assetName: "Heritage Bank",
    quantity: 50_000_000,
    price: 16.0,
    amount: 800,
    status: "Settled",
    notes: "Partial exit, near target weight",
  },
  {
    id: "TXN-0239",
    date: "2026-05-24",
    type: "Rebalance",
    holdingId: "HPL",
    assetName: "Real Estate Portfolio",
    amount: 0,
    status: "Processing",
    notes: "Internal revaluation rebalance",
  },
  {
    id: "TXN-0238",
    date: "2026-05-23",
    type: "Dividend",
    holdingId: "TCP",
    assetName: "Transcorp Plc",
    amount: 420,
    status: "Settled",
    notes: "Final FY2025 dividend — ₦0.051/share",
  },
  {
    id: "TXN-0237",
    date: "2026-05-22",
    type: "Coupon",
    holdingId: "FGNB31",
    assetName: "FGN Bond 2031",
    amount: 1_178,
    status: "Settled",
    notes: "Semi-annual coupon @ 15.5% p.a.",
  },
  {
    id: "TXN-0236",
    date: "2026-05-20",
    type: "Buy",
    holdingId: "TCP",
    assetName: "Transcorp Plc",
    quantity: 10_000_000,
    price: 8.29,
    amount: -82.9,
    status: "Settled",
    notes: "Tactical top-up on pre-results momentum",
  },
  {
    id: "TXN-0235",
    date: "2026-05-19",
    type: "Maturity",
    holdingId: "CBN91",
    assetName: "T-Bills 91-Day",
    amount: 5_200,
    status: "Settled",
    notes: "Principal redemption — proceeds rolled into 182-day",
  },
  {
    id: "TXN-0234",
    date: "2026-05-15",
    type: "Buy",
    holdingId: "UCA",
    assetName: "United Capital Plc",
    quantity: 20_000_000,
    price: 15.19,
    amount: -303.8,
    status: "Settled",
  },
  {
    id: "TXN-0233",
    date: "2026-05-10",
    type: "Dividend",
    holdingId: "APG",
    assetName: "Africa Prudential Plc",
    amount: 174,
    status: "Settled",
    notes: "Interim dividend",
  },
  {
    id: "TXN-0232",
    date: "2026-05-08",
    type: "Capital Call",
    holdingId: "AGF3",
    assetName: "Africa Growth Fund III",
    amount: -3_280,
    status: "Settled",
    notes: "Capital call #3 — co-investment in Lagos data centre",
  },
  {
    id: "TXN-0231",
    date: "2026-04-30",
    type: "Coupon",
    holdingId: "DGB26",
    assetName: "Dangote Industries Bond",
    amount: 368,
    status: "Settled",
    notes: "Quarterly coupon @ 14.75%",
  },
  {
    id: "TXN-0230",
    date: "2026-04-22",
    type: "Buy",
    holdingId: "CBN182",
    assetName: "T-Bills 182-Day",
    amount: -5_000,
    status: "Settled",
    notes: "Cash deployment from matured 91-day proceeds",
  },
  {
    id: "TXN-0229",
    date: "2026-04-10",
    type: "Sell",
    holdingId: "TCP",
    assetName: "Transcorp Plc",
    quantity: 200_000_000,
    price: 7.95,
    amount: 1_590,
    status: "Settled",
    notes: "Partial profit-taking post Q1 results",
  },
  {
    id: "TXN-0228",
    date: "2026-03-28",
    type: "Buy",
    holdingId: "HTA",
    assetName: "Leadway Tower Abuja",
    amount: -4_200,
    status: "Settled",
    notes: "Completion payment on tower development",
  },
  {
    id: "TXN-0227",
    date: "2026-03-15",
    type: "Dividend",
    holdingId: "UCA",
    assetName: "United Capital Plc",
    amount: 280,
    status: "Settled",
  },
];

/* ─────────────────────────────────────────────────────────
   Stress Test Scenario Definitions
   ───────────────────────────────────────────────────────── */
export const STRESS_SCENARIOS: Omit<StressScenario, "impact" | "pct">[] = [
  {
    scenario: "2008 Global Financial Crisis",
    shocks: {
      Equity: -0.4,
      "Fixed Income": -0.05,
      "Real Estate": -0.22,
      "Private Equity": -0.35,
      Alternatives: -0.28,
      Cash: 0,
    },
    severity: "high",
  },
  {
    scenario: "2016 Nigeria Recession",
    shocks: {
      Equity: -0.3,
      "Fixed Income": -0.08,
      "Real Estate": -0.16,
      "Private Equity": -0.24,
      Alternatives: -0.2,
      Cash: 0,
    },
    severity: "medium",
  },
  {
    scenario: "Oil Price Crash (−50%)",
    shocks: {
      Equity: -0.2,
      "Fixed Income": -0.04,
      "Real Estate": -0.1,
      "Private Equity": -0.18,
      Alternatives: -0.1,
      Cash: 0,
    },
    severity: "medium",
  },
  {
    scenario: "NGN Devaluation (−30%)",
    shocks: {
      Equity: -0.12,
      "Fixed Income": -0.06,
      "Real Estate": -0.08,
      "Private Equity": -0.1,
      Alternatives: -0.08,
      Cash: 0.02,
    },
    severity: "low",
  },
  {
    scenario: "CBN Rate Hike (+300 bps)",
    shocks: {
      Equity: -0.09,
      "Fixed Income": -0.14,
      "Real Estate": -0.07,
      "Private Equity": -0.05,
      Alternatives: -0.05,
      Cash: 0.04,
    },
    severity: "low",
  },
];

/* YTD monthly performance data (portfolio vs NGSE All-Share) */
export const MONTHLY_RETURNS = [
  { period: "Jan", portfolioReturn: 0.031, benchmarkReturn: 0.024 },
  { period: "Feb", portfolioReturn: 0.024, benchmarkReturn: 0.018 },
  { period: "Mar", portfolioReturn: -0.003, benchmarkReturn: -0.008 },
  { period: "Apr", portfolioReturn: 0.038, benchmarkReturn: 0.032 },
  { period: "May", portfolioReturn: 0.028, benchmarkReturn: 0.022 },
];
